# Generated by Django 5.1.3 on 2024-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('Not urgent', 'not_urgent'), ('Very urgent', 'very_urgent'), ('Urgent', 'urgent')], default='Not urgent', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('31-40', '31-40'), ('Under 15', 'Under 15'), ('15-17', '15-17'), ('51-60', '51-60'), ('18-20', '18-20'), ('41-50', '41-50'), ('61+', '61+'), ('21-30', '21-30')], default='21-30', max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary/Other', 'Non-Binary/Other')], default='Male', max_length=16),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('ID', 'ID'), ('NV', 'NV'), ('AK', 'AK'), ('AZ', 'AZ'), ('HI', 'HI'), ('UT', 'UT'), ('MN', 'MN'), ('IN', 'IN'), ('NM', 'NM'), ('NC', 'NC'), ('CO', 'CO'), ('MT', 'MT'), ('OH', 'OH'), ('GA', 'GA'), ('OR', 'OR'), ('CT', 'CT'), ('AR', 'AR'), ('WY', 'WY'), ('MO', 'MO'), ('ND', 'ND'), ('TN', 'TN'), ('OK', 'OK'), ('VT', 'VT'), ('NY', 'NY'), ('CA', 'CA'), ('LA', 'LA'), ('MS', 'MS'), ('IA', 'IA'), ('SC', 'SC'), ('WV', 'WV'), ('NE', 'NE'), ('DE', 'DE'), ('MI', 'MI'), ('ME', 'ME'), ('NJ', 'NJ'), ('FL', 'FL'), ('TX', 'TX'), ('WI', 'WI'), ('MD', 'MD'), ('PA', 'PA'), ('KS', 'KS'), ('NH', 'NH'), ('RI', 'RI'), ('VA', 'VA'), ('AL', 'AL'), ('MA', 'MA'), ('WA', 'WA'), ('KY', 'KY'), ('IL', 'IL'), ('SD', 'SD')], default='AL', max_length=2),
        ),
    ]
