# Generated by Django 5.1.3 on 2024-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_urgency_alter_volunteer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('Not urgent', 'not_urgent'), ('Urgent', 'urgent'), ('Very urgent', 'very_urgent')], default='Not urgent', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('15-17', '15-17'), ('21-30', '21-30'), ('18-20', '18-20'), ('31-40', '31-40'), ('51-60', '51-60'), ('61+', '61+'), ('41-50', '41-50'), ('Under 15', 'Under 15')], default='21-30', max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Non-Binary/Other', 'Non-Binary/Other'), ('Female', 'Female')], default='Male', max_length=16),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('IN', 'IN'), ('MI', 'MI'), ('TX', 'TX'), ('IA', 'IA'), ('AL', 'AL'), ('UT', 'UT'), ('AZ', 'AZ'), ('VA', 'VA'), ('WV', 'WV'), ('MA', 'MA'), ('DE', 'DE'), ('ND', 'ND'), ('IL', 'IL'), ('MS', 'MS'), ('PA', 'PA'), ('MN', 'MN'), ('NJ', 'NJ'), ('ID', 'ID'), ('NE', 'NE'), ('SC', 'SC'), ('HI', 'HI'), ('WY', 'WY'), ('AK', 'AK'), ('AR', 'AR'), ('OH', 'OH'), ('CO', 'CO'), ('OK', 'OK'), ('NC', 'NC'), ('KS', 'KS'), ('CT', 'CT'), ('NY', 'NY'), ('MD', 'MD'), ('ME', 'ME'), ('MT', 'MT'), ('FL', 'FL'), ('RI', 'RI'), ('NV', 'NV'), ('OR', 'OR'), ('MO', 'MO'), ('KY', 'KY'), ('LA', 'LA'), ('SD', 'SD'), ('NH', 'NH'), ('VT', 'VT'), ('WA', 'WA'), ('CA', 'CA'), ('GA', 'GA'), ('NM', 'NM'), ('TN', 'TN'), ('WI', 'WI')], default='AL', max_length=2),
        ),
    ]
